# Define the version of the Compose file format
version: '3.8'

# Define the services that will be run
services:
  # Define the MongoDB service
  mongodb:
    # Use the official MongoDB image from Docker Hub
    image: mongo
    # Name the MongoDB container
    container_name: mongodb
    # Map port 27017 on the host to port 27017 on the container
    ports:
      - "27017:27017"

  # Define the Flask application service
  flaskapp:
    # Build the Flask application image using the Dockerfile in the current directory
    build: .
    # Name the Flask application container
    container_name: flaskapp
    # Map port 5000 on the host to port 5000 on the container
    ports:
      - "5000:5000"
    # Specify that the flaskapp service depends on the mongodb service
    depends_on:
      - mongodb
    # Set environment variables for the Flask application
    environment:
      # Define the MongoDB URI to connect the Flask application to the MongoDB container
      - MONGO_URI=mongodb://mongodb:27017/github_webhooks
